### ISSUE TITLE
find out the end of typing?

### ISSUE THREAD

**Issue by hosseinjafari9574** [iamporus/TypedTextView#2]
Hi @iamporus 
thank you for your nice lib, I LOVE it :)

I want to add a button to screen at the end of typing. How can I find out when typing finished?

thanks in advanced.

**Comment by iamporus** [comment]
Great that you liked it. 
One way you can achieve detect the end of typing is by using the `OnCharacterTypedListener` interface. 
Here's how I'd do it.

```
//Set text to be typed
String textToType = "Once there lived a monkey in a jamun tree by a river. The monkey was alone. He had no friends, no family, but he was happy and content.";

typedTextView.setTypedText( textToType );
  
//Set listener to invoke other actions based on status.
typedTextView.setOnCharacterTypedListener( new TypedTextView.OnCharacterTypedListener()
{
  @Override
  public void onCharacterTyped( char character, int index )
  {
    if(index == textToType.length() - 1)
    {
        Log.d( TAG, "Typing ended. Show the button." );
    }
  }
});

```
Otherwise, you can always fork and add another hook inside OnCharacterTypedListerner (say `onTypingEnded()`)  to provide a callback on typing has ended.
You can call that method [here](https://github.com/iamporus/TypedTextView/blob/master/typedtextview/src/main/java/com/prush/typedtextview/TypedTextView.java#L163).

**Comment by hosseinjafari9574** [comment]
yeah I got it.  :)

thanks you so much @iamporus
